INSERT INTO "DoctorSpecializations" ("Id", "Name")
VALUES (1, 'Allergy and immunology'),
       (2, 'Anesthesiology'),
       (3, 'Dermatology'),
       (4, 'Diagnostic radiology'),
       (5, 'Emergency medicine'),
       (6, 'Family medicine'),
       (7, 'Internal medicine'),
       (8, 'Medical genetics'),
       (9, 'Neurology'),
       (10, 'Nuclear medicine'),
       (11, 'Obstetrics and gynecology'),
       (12, 'Ophthalmology'),
       (13, 'Pathology'),
       (14, 'Pediatrics'),
       (15, 'Physical medicine and rehabilitation'),
       (16, 'Preventive medicine'),
       (17, 'Psychiatry'),
       (18, 'Radiation oncology'),
       (19, 'Surgery'),
       (20, 'Urology');